v1.0.1

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,89 +1,14 @@
 #!/bin/bash
 
-source <(otc-task-include lib/filesystem.sh)
-source <(otc-task-include lib/helm.sh)
-source <(otc-task-include lib/assert.sh)
-source <(otc-task-include lib/console.sh)
+set -e
+CONFIGURATION=$1
+if [ -z $CONFIGURATION ]
+then
+  echo "Missing CONFIGURATION"
+  echo "Usage: $0 CONFIGURATION"
+  exit 1
+fi
 
-# Param helm_dir - Helm chart directory
-# Param namespace
-# Param custom_name (OPTIONAL)
-# Param custom_values (OPTIONAL) - custom helm values file (path relative to helm_dir)
-# Look for ENVIRONMENT_NAME environment var
-function main
-{
-	local helm_dir="$1"
-	local namespace="$2"
-	local custom_name="$3" #optional
-	local custom_values="$4" #optional
-
-	if ! [ -z "$custom_values" ]
-	then
-		echo "Using '$custom_values' as helm values." >&2
-	fi
-
-	assert-not-empty helm_dir
-	assert-not-empty namespace
-	
-	local release_name_file=$(mktemp -t "release_name-XXXXXXXX")
-	local helm_deploy_status_code=0 # assume success
-
-	helm-deploy "$helm_dir" "$namespace" "$custom_name" "$custom_values" \
-		> $release_name_file || helm_deploy_status_code=$?
-
-	if [ "$helm_deploy_status_code" -eq "$HELM_DEPLOY_CUSTOM_VALUES_FILE_NOT_FOUND" ]
-	then
-		echo "----------------------------------------------------------------------------------------------------" >&2
-		echo "O arquivo com os valores para o ambiente '$ENVIRONMENT_NAME' nao foi encontrado, logo nao " >&2
-		echo "sera possivel realizar o deploy neste ambiente." >&2
-		echo "" >&2
-		echo "Para corrigir este problema, adicione o arquivo '$custom_values' no diretorio do helm chart," >&2
-		echo "normalmente Kubernetes.Helm." >&2
-		echo "" >&2
-		echo "IMPORTANTE: Dados sensiveis, como strings de conexao, credenciais para servicos externos, " >&2
-		echo "            etc, nao devem ser inseridos neste arquivo. Para isso, deverao ser utilizados " >&2
-		echo "            secrets (em caso de dúvidas, conversar com arquitetura/infra-estrutura)." >&2
-		echo "----------------------------------------------------------------------------------------------------" >&2
-		exit 103
-	fi
-
-	local release_name=$(cat $release_name_file)
-	
-	if [ -z "$release_name" ]
-	then
-		red "Could not get release name." >&2
-		echo $HELM_GENERAL_DEPLOY_ERROR_MESSAGE >&2
-
-		exit 109
-	fi
-
-	rm $release_name_file
-
-	if [ "$helm_deploy_status_code" -ne "0" ]
-	then
-		local history_count=$(($(helm history $release_name | wc -l) - 1))
-
-		if ! echo $history_count | egrep '^[0-9]+$' > /dev/null 2>&1
-		then
-			red "Could not get history for '$release_name'. At this point, release '$release_name' " >&2
-			red "should exists, neither it successfully deployed or not." >&2
-			echo $HELM_GENERAL_DEPLOY_ERROR_MESSAGE >&2
-
-			exit 117
-		fi
-
-		if [ "$history_count" -gt "0" ]
-		then
-			red "As helm deploy failed, rolling back to previous revision." >&2
-			assert-success helm rollback $release_name 0 >&2
-		else
-			red "Seems that is the first '$release_name' release." >&2
-			red "As helm deploy has failed, going to deleting it." >&2
-			assert-success helm delete $release_name --purge >&2
-		fi
-	fi
-
-	exit $helm_deploy_status_code
-}
-
-main "$@"
+dotnet clean ./Source
+rm -Rf $(find ./Source | egrep '/(bin|obj)$')
+dotnet build ./Source --configuration $CONFIGURATION
diff --git a/helm-dry-run b/helm-dry-run
--- a/helm-dry-run
+++ b/helm-dry-run
@@ -1,17 +1,15 @@
 #!/bin/bash
 
-set -e
-WORK_DIR=$(pwd)    
-for HELMPATH in $(find -name Kubernetes.Helm)
-do
-  cd $HELMPATH
-  echo "Validating Helm (dry-run)"
+source <(otc-task-include lib/assert.sh)
+source <(otc-task-include lib/vsts.sh)
+source <(otc-task-include lib/console.sh)
+source <(otc-task-include lib/vsts-pr-statuses.sh)
 
-  if ! helm install . --dry-run > /dev/null 2>&1
-  then
-    echo "helm dry-run failed"
-    helm install . --dry-run --debug
-    exit 1
-  fi
-  cd $WORK_DIR
-done
+assert-not-empty SYSTEM_PULLREQUEST_PULLREQUESTID
+
+# flag create at deploy preview step that means the deploy 
+# preview failed in a regular way (not crashed)
+if ! [ -f "deploy-preview-regular-fail" ] 
+then
+	! finalize-pr-statuses $SYSTEM_PULLREQUEST_PULLREQUESTID
+fi
