v5.0.2

diff --git a/otc-task-local b/otc-task-local
--- a/otc-task-local
+++ b/otc-task-local
@@ -1,8 +1,33 @@
 #!/bin/bash
 
-source <(otc-task-include lib/filesystem.sh)
-source <(otc-task-include lib/npm.sh)
-source <(otc-task-include lib/assert.sh)
-source <(otc-task-include lib/console.sh)
+# EXECUTE otc-task locally for development
 
-npm-build $@
+TASKS_DIRECTORY=$(realpath $(dirname $0))
+
+OTC_TASK_INCLUDE_LOCAL_TASK_NOT_FOUND=34
+
+function otc-task-include
+{
+	local task_path="${TASKS_DIRECTORY}/$1"
+ 	
+ 	if ! [ -f "$task_path" ]
+ 	then
+ 		echo "File '$task_path' not found." >&2
+
+ 		return $OTC_TASK_INCLUDE_LOCAL_TASK_NOT_FOUND
+ 	fi
+
+ 	cat $task_path
+}
+
+script_path="${TASKS_DIRECTORY}/$1"
+
+if ! [ -f "$script_path" ]
+then
+	echo "File '$script_path' not found." >&2
+
+	exit 43
+fi
+
+shift
+source $script_path
